### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by andrewheusser**
update serialport version

### CODE REVIEW

**Comment by pushtheworldllc** [comment]
What are the conflicts @teonbrooks ?

**Comment by teonbrooks** [comment]
Oh I fixed it directly so I will close this now

**Comment by teonbrooks** [comment]
Master has the fix. I did it on @andrewheusser's account directly

**Comment by pushtheworldllc** [comment]
sweet

**Comment by pushtheworldllc** [comment]
Should you really hot fix shit like this?

**Comment by teonbrooks** [comment]
hey @pushtheworldllc, can you check to make sure the updated serialport is fine. the build (https://travis-ci.org/OpenBCI/openbci-js-sdk/builds/122671778) worked correctly but I want to make sure I didn't mess up anything before you do the 0.3.1 rollout

**Pull request closed without merging**
