### PR TITLE
ENH/ADD sntp time sync methods

### PR DESCRIPTION
**Pull request by pushtheworldllc**
I added a key function for SNTP, called `.sntpNow()` I also simply extended sntp class so we could call into that if need by in the future.

### CODE REVIEW

**Comment by teonbrooks** [comment]
LGTM. just curious, have you tested this code yet on real data? this is useful to syncing the board to time server, does this mean we need to instruct computer-side app to implement a similar protocol when the computer is connected to the internet?

**Comment by pushtheworldllc** [comment]
No! The firmware has not been implemented yet!! These are the functions that are required to talk with the board though!

**Comment by pushtheworldllc** [comment]
Firmware is happening by next Thursday

**Comment by pushtheworldllc** [comment]
So you will see another PR come thru soon that adds V4 functionality

**Comment by teonbrooks** [comment]
v4 of the firmware? i know that the board has v3 printed on that, but I am assuming that this is just the 3rd iteration of the board design. that is separate from the board's firmware, do you know?

**Comment by pushtheworldllc** [comment]
oh shit true, lol can we merge this and discuss how i have been calling my software update the wrong thing in another form haha

**Comment by teonbrooks** [comment]
sure, merging now. feel free to make an issue about the name

**Pull request merged**
